# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-check
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.371
    hooks:
    -   id: pyright
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - args:
      - --profile=black
      id: isort
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.1]
